
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ShootingStars } from "@/components/ui/shooting-stars";
import {ClerkProvider} from "@clerk/nextjs";
import { SidebarComponent } from "@/components/SidebarComponent";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-y-auto max-h-screen scrollbar-thin scrollbar-thumb-purple-600 scrollbar-track-gray-800/50  antialiased`}
      >

        <SidebarComponent isLoading={false}>
        <ShootingStars  />
        <div className="relative h-full w-full bg-slate-950">
        <div className="absolute bottom-0 left-0 right-0 top-0  bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px]  [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>

     
        {children}
        </div>
        </SidebarComponent>
        
      </body>
    </html>
    </ClerkProvider>
  );
}